project:
  type: website

website:
  
  navbar:
    title: "Nabil Salehiyan"
    right: 
    - text: "Contact me"
      icon: fa-envelope-o
      href: mailto:nabilsalehiyan@gmail.com                    
    - text: "GitHub"
      icon: fa-github
      href: https://github.com/nabilsalehiyan

    - href: index.html
     
    - href: multivariate analysis cookbook .html
      text: Multivariate Analysis Methods
    - href: project.html
      text: Project
    - href: resume.nabilsalehiyan2023.pdf
      text: Resume
      icon: fa-file-pdf-o
   
    - text: Labs
      menu:
        - href: lab02.html
        - href: lab01.html
    - text: Assignments
      menu:
      - href: assignment1.html
        text: assignment1
      - href: assignment2.html
        text: assignment2
      
      
     
        
    left:
      - href: index.html
        text: Home
        icon: fa-home
      - href: about.html
        text: About
        icon: fa-user
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

