project:
  type: website

website:
  
  navbar:
    title: "Nabil Salehiyan"
    left: 
    - text: "Contact me"
      icon: fa-envelope-o
      href: mailto:nabilsalehiyan@gmail.com                    
    - text: "GitHub"
      icon: fa-github
      href: https://github.com/nabilsalehiyan
    - href: nabilsalehiyan.resume214.pdf
      text: "Resume"
      icon: fa-file-pdf-o

    - href: index.html
     
    - href: multivariate analysis cookbook.html
      text: Multivariate Analysis Methods
    
    - text: Projects
      menu: 
      - href: projectloan.combined.html
        text: Loan Status Prediction
      - href: autism-discrimination.html
        text: MRI Autism Prediction 
    - href: nabilsalehiyan.resume214.pdf
   
   
    - text: Labs
      menu:
      - href: Lab01.html
        text: Basic Commands in R - Functions
      - href: Lab02.html
        text: Basic Commands in R - Data
      
    - text: Assignments
      menu:
      - href: assignment1.html
        text: Prediction VS Explanation
      - href: assignment2.html
        text: Teds_2016 Exploratory Analysis
      
      
     
        
    right:
      - href: index.html
        text: Home
        icon: fa-home
      - href: about.html
        text: About
        icon: fa-user
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

