project:
  type: website

website:
  
  navbar:
    
    font-size: smaller;
    left: 
    - text: "Contact me"
      icon: fa-envelope-o
      href: mailto:nabilsalehiyan@gmail.com                    
    - text: "GitHub"
      icon: fa-github
      href: https://github.com/nabilsalehiyan
    - href: nabilsalehiyan.resume301.pdf
      text: "Resume"
      icon: fa-file-pdf-o

    - href: index.html
     
    - href: multivariate analysis cookbook.html
      text: Multivariate Analysis Methods
    
    - text: Projects
      menu: 
      - href: projectloan.combined.html
        text: Loan Status Prediction
      - href: autism-discrimination.html
        text: MRI Autism Prediction 
      - href: projectproposal.html
        text: police response project proposal 
   
   
    - text: Labs
      menu:
      - href: Lab01.html
        text: Basic Commands in R - Functions
      - href: Lab02.html
        text: Basic Commands in R - Data
      
    - text: Data Mining Assignments
      menu:
      - href: Explanation vs Prediction.pdf
        text: To Explain or Predict
      - href: assignment2.html
        text: Exploratory Analysis
      - href: assignment03.qmd
        text: Multiple Regression 
      - href: assignment04.qmd
        text: Machine Learning Methods 
      - href: assignment05.qmd
        text: Text Mining 
      - href: assign06.qmd
        text: Linear and Logistic Regression
      
        
      
      
     
        
    right:
      - href: index.html
        text: Home
        icon: fa-home
      
      

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    

editor: visual

